# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbf4a5c3cd1c32c89919c12fcf3a465e85dca4c7be1eb86402e5267e63dd41cacdb4402d422e9bdf7d46d84322b54a7b58f7fa41d599b2815c638a9b99eaf0a4

test:
  secret_key_base: a94c802fd2c1a018915ca4681d59776341eab9e3c86ddf7688d26b4647048ff72bcea5b6bff17cdf154397ab4e46176f513090f7a3408aa46396f1d3a527b840

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
